### ISSUE TITLE
Change CA cert

### ISSUE THREAD

**Issue by msg7086** [denisio/seno-blockchain#2]
Change `chia_ca.key` to avoid connecting to other clients such as Chia or CGN.

**Comment by denisio** [comment]
Thanks

**Comment by itsyourskill** [comment]
Where to change chia_ca.key

**Comment by vanthoi** [comment]
> Thanks

You change the ssl is enough then why need to change the name and directory like that? When opening the daemon, if the version is different, the daemon will update the cert again!

**Comment by denisio** [comment]
Just force switch for old client
